/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ldts.hero;



public class App {


    public static void main(String[] args) {
        try{
            Game game = new Game();
            game.run();
        } catch(Exception pog){
            pog.printStackTrace();
        }
        
    }
}
